using System.Collections.Generic;

using PHED_CGRC.MANAGE_HOLIDAYSLIST_CONFIG;
namespace MISReport.Repository.Interfaces.MANAGE_HOLIDAYSLIST_CONFIG
{
  public interface IMANAGE_HOLIDAYSLIST_CONFIGRepository
  {
  	 Task<int> INSERT_MANAGE_HOLIDAYSLIST_CONFIG(MANAGE_HOLIDAYSLIST_CONFIG_Model TBL);
	
	 Task<int> UPDATE_MANAGE_HOLIDAYSLIST_CONFIG(MANAGE_HOLIDAYSLIST_CONFIG_Model TBL);
	
	 Task<int> DELETE_MANAGE_HOLIDAYSLIST_CONFIG(MANAGE_HOLIDAYSLIST_CONFIG_Model TBL);
	
	 Task<List<VIEWMANAGE_HOLIDAYSLIST_CONFIG>> VIEW_MANAGE_HOLIDAYSLIST_CONFIG(MANAGE_HOLIDAYSLIST_CONFIG_Model TBL);
	
	 Task<List<EDITMANAGE_HOLIDAYSLIST_CONFIG>> EDIT_MANAGE_HOLIDAYSLIST_CONFIG(MANAGE_HOLIDAYSLIST_CONFIG_Model TBL);
	
}
}
