using System.Collections.Generic;

using PHED_CGRC. MANAGE_SUBCATEGORYMASTER;
namespace CommonMaster.Repository.Interfaces.MANAGE_SUBCATEGORYMASTER
{
  public interface IMANAGE_SUBCATEGORYMASTERRepository
  {
  	 Task<int> INSERT_MANAGE_SUBCATEGORYMASTER(MANAGE_SUBCATEGORYMASTER_Model TBL);
	
	 Task<int> UPDATE_MANAGE_SUBCATEGORYMASTER(MANAGE_SUBCATEGORYMASTER_Model TBL);
	
	 Task<int> DELETE_MANAGE_SUBCATEGORYMASTER(MANAGE_SUBCATEGORYMASTER_Model TBL);
	
	 Task<List<VIEWMANAGE_SUBCATEGORYMASTER>> VIEW_MANAGE_SUBCATEGORYMASTER(MANAGE_SUBCATEGORYMASTER_Model TBL);
	
	 Task<List<EDITMANAGE_SUBCATEGORYMASTER>> EDIT_MANAGE_SUBCATEGORYMASTER(MANAGE_SUBCATEGORYMASTER_Model TBL);
	
}
}
